/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */

/* "GUI debugging code" */
/* #undef EG_DEBUG */

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `z' library (-lz). */
#define HAVE_LIBZ 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <zlib.h> header file. */
#define HAVE_ZLIB_H 1

/* Name of package */
#define PACKAGE "beebem"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* "Fake windows registry filename" */
#define REG_FILENAME "beebem.registry"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.0.13"

/* "Disable level indicator" */
#define WITHOUT_LEVEL_INDICATOR 1

/* "without realtime slider" */
/* #undef WITHOUT_REALTIME_SLIDER */

/* "Disable all __LINE__ shenanigans" */
#define WITHOUT_SHENANIGANS 1

/* "without annoying welcome message" */
/* #undef WITHOUT_WELCOME_MESSAGE */

/* "with additional debugging" */
/* #undef WITH_DEBUG_OUTPUT */

/* "with econet support (UNIX only)" */
#define WITH_ECONET 1

/* "With forced colormap for 8 bit displays" */
#define WITH_FORCED_CM 1

/* "With Fullscreen FPS" */
#define WITH_FS_FPS 1

/* "With system 'cp' command" */
#define WITH_SYSTEM_CP 1

/* "Enable UNIX extras" */
#define WITH_UNIX_EXTRAS 1
